### ISSUE TITLE
JSONDecodeError - Bot not working

### ISSUE THREAD

**Issue by zacharimayer** [yurilaaziz/instabot.py#14]
Check this or we will delete your issue. (fill in the checkbox with an X like so: [x])
- [x] I have searched for other issues with the same problem or similar feature requests. 

#### Select one:
- [x] Bug
- [ ] Feature Request
- [ ] Technical Help (Please don't create an issue, join the facebook group or telegram channel)
- [ ] Other

#### Environment
- [ ] Are you hosting the bot on a VPS or other Cloud hosting?
- [ ] Are you running the code on your phone 
- [x] If so, have you tried running the code on your local machine?

```
Running on local machine - MacOS env, also tried in Rasp pi and same error comes up
```

#### Operating System? (include version)
- [x] macOS
- [ ] Windows
- [x] Rasbian Linux Raspberry PI (include flavour)
- [ ] Linux (include flavour)
- [ ] Android (include terminal)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/instabot/bot.py", line 484, in get_media_id_by_tag
    all_data = json.loads(r.text)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/bin/neo-instabot", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/instabot/__main__.py", line 345, in main
    bot.run()
  File "/usr/local/lib/python3.6/site-packages/instabot/bot.py", line 728, in run
    self.logger.debug(f"Retrieved {len(medias_raw)} medias")
TypeError: object of type 'NoneType' has no len()
```

#### Python Version Requirement
- [x] I am using Python 3.6 or above

#### Exact Python Version?
```
3.6
```

#### Pip Version?
```
0.5.9
```

#### Instabot Version?
```
0.6.0
```

#### How you use the instabot
- [x] instabot-py -c my-configfile.yml (my-configfile.yml is an example you may have a different file )
- [ ] instabot-py --login LOGIN --password PASSWORD
- [ ] instabot-py 
- [ ] example.py (Deprecated, please install newer version) 

#### Description of your issue

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/instabot/bot.py", line 484, in get_media_id_by_tag
    all_data = json.loads(r.text)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/bin/neo-instabot", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/instabot/__main__.py", line 345, in main
    bot.run()
  File "/usr/local/lib/python3.6/site-packages/instabot/bot.py", line 728, in run
    self.logger.debug(f"Retrieved {len(medias_raw)} medias")
TypeError: object of type 'NoneType' has no len()
```

#### Config

```
---
login : "login"
password : "password"
debug: 0
follow_time: 800
like_per_day: 100
like_per_run: 100
comments_per_day: 0
max_like_for_one_tag: 100
follow_per_day: 0
follow_time: 360
start_at_h: 9
start_at_m: 0
end_at_h: 22
end_at_m: 0
unfollow_per_day: 0
unfollow_break_min: 3
unfollow_break_max: 17
unfollow_selebgram: false
unfollow_probably_fake: false
unfollow_inactive: false
unfollow_recent_feed: false
tag_list:
tags

```

**Comment by x-raay** [comment]
try changing your password from the Instagram website and relogin from the script
