### ISSUE TITLE
Please fix @username@

### ISSUE THREAD

**Issue by onerfusion** [yurilaaziz/instabot.py#24]
It's giving me this following error on the latest version

Traceback (most recent call last):                           File "/data/data/com.termux/files/usr/bin/neo-instabot", line 10, in <module>                                           sys.exit(main())
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/instabot/__main__.py", line 345, in main
    bot.run()                                                File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/instabot/bot.py", line 740, in run                    self.new_auto_mod_comments(media)                        File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/instabot/bot.py", line 1012, in new_auto_mod_comments
    comment_text = comment_text.replace("@username@", media["node"]["owner"]["username"])                             KeyError: 'username'

**Comment by Redrum2210** [comment]
> It's giving me this following error on the latest version
> 
> 
> 
> 
> 
> 
> Traceback (most recent call last):                           File "/data/data/com.termux/files/usr/bin/neo-instabot", line 10, in <module>                                           sys.exit(main())
>   File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/instabot/__main__.py", line 345, in main
>     bot.run()                                                File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/instabot/bot.py", line 740, in run                    self.new_auto_mod_comments(media)                        File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/instabot/bot.py", line 1012, in new_auto_mod_comments
>     comment_text = comment_text.replace("@username@", media["node"]["owner"]["username"])                             KeyError: 'username'
